- project:
    name: openstack/pyghmi
    check:
      jobs:
        - tempest-devstack-ironic-pxe_ipmitool-pyghmi-src:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - tempest-devstack-ironic-pxe_ipmitool-pyghmi-src:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
