#!/bin/bash
cd `dirname $0`
# If not PBR, use the setup.py.tmpl
python -c 'import pbr' || ./makesetup
VERSION=`python setup.py --version`
python setup.py sdist
py2dsc dist/pyghmi-$VERSION.tar.gz
shopt -s extglob
cd deb_dist/!(*.orig)/
dpkg-buildpackage -rfakeroot -uc -us -i
cd -
rm -rf $(find deb_dist -mindepth 1 -maxdepth 1 -type d)
rm $1/*pyghmi*
cp deb_dist/* $1/
